server:
  port: 10086

weather: 
  cron: '0 0/2 * * * ?' #定时执行，示例：每30分钟执行一次
  base-url: http://www.nmc.cn/publish/precipitation/1-day.html #要爬取的网页
  save-root-path: /home/weather/img #图片存储路径
  url-class-name: .container .row .col-xs-10 .bgwhite .p-wrap .p-nav.nav2 ul li a #html 中的页面标签，请确认后再修改
  img-id-name: imgpath #html 中的图片id，请确认后再修改
  img-cut-range: 
    need-cut: true #需要对图片进行切割
    x: 580
    y: 370
    width: 150
    height: 80
mail: #抓取失败时，发送邮件通知
  title: 中央气象台天气预报数据抓取 #邮件标题
  sslEnable: false
  host: smtp.qq.com
  socketFactoryPort: 587 #发送邮件服务器： smtp.qq.com，使用SSL，端口号465或587
  from: test@qq.com #发送者
  pass: 授权信息 #授权信息
  tos: # 接收者
    - superbeyone@outlook.com

